stages:
  convert_baseline:
    cmd: python3 scripts/convert_sas_to_feather.py --input_filename data/raw_data/merged_baseline.sas7bdat
      --output_filename data/raw_data/baseline.feather
    deps:
    - data/raw_data/merged_baseline.sas7bdat
    - scripts/convert_sas_to_feather.py
    outs:
    - data/raw_data/baseline.feather
  convert_inr:
    cmd: python3 scripts/convert_sas_to_feather.py --input_filename data/raw_data/merged_inr.sas7bdat
      --output_filename data/raw_data/inr.feather
    deps:
    - data/raw_data/merged_inr.sas7bdat
    - scripts/convert_sas_to_feather.py
    outs:
    - data/raw_data/inr.feather
  convert_events:
    cmd: python3 scripts/convert_sas_to_feather.py --input_filename data/raw_data/merged_events.sas7bdat
      --output_filename data/raw_data/events.feather
    deps:
    - data/raw_data/merged_events.sas7bdat
    - scripts/convert_sas_to_feather.py
    outs:
    - data/raw_data/events.feather
  preprocess:
    cmd: python3 scripts/preprocess_combine_af.py --baseline_path data/raw_data/baseline.feather
      --inr_path data/raw_data/inr.feather --events_path data/raw_data/events.feather
      --output_directory data/clean_data
    params:
    - preprocess
    - data
    deps:
    - data/raw_data/baseline.feather
    - data/raw_data/events.feather
    - data/raw_data/inr.feather
    - scripts/preprocess_combine_af.py
    outs:
    - data/clean_data/baseline.feather
    - data/clean_data/inr.feather
    - data/clean_data/events.feather
    - data/clean_data/merged.feather
    - data/clean_data/train_data.feather
    - data/clean_data/val_data.feather
    - data/clean_data/test_data.feather
    - data/auditing/impute_inr_and_dose.feather
    - data/auditing/merge_inr_baseline.feather
    - data/auditing/merge_inr_events.feather
    - data/auditing/merge_trials_and_remove_outlying_doses.feather
    - data/auditing/preprocess_all_baseline.feather
    - data/auditing/preprocess_all_events.feather
    - data/auditing/preprocess_all_inr.feather
    - data/auditing/preprocess_aristotle.feather
    - data/auditing/preprocess_engage_rocket.feather
    - data/auditing/preprocess_rely.feather
    - data/auditing/remove_short_trajectories.feather
    - data/auditing/split_data_test.feather
    - data/auditing/split_data_train.feather
    - data/auditing/split_data_val.feather
    - data/auditing/split_trajectories_at_events.feather
    - data/auditing/split_trajectories_at_gaps.feather
  audit_preprocess:
    cmd: python3 scripts/audit_combine_preprocessing.py > output/combine_preprocess_audit.txt
    deps:
    - data/auditing/impute_inr_and_dose.feather
    - data/auditing/merge_inr_baseline.feather
    - data/auditing/merge_inr_events.feather
    - data/auditing/merge_trials_and_remove_outlying_doses.feather
    - data/auditing/preprocess_all_baseline.feather
    - data/auditing/preprocess_all_events.feather
    - data/auditing/preprocess_all_inr.feather
    - data/auditing/preprocess_aristotle.feather
    - data/auditing/preprocess_engage_rocket.feather
    - data/auditing/preprocess_rely.feather
    - data/auditing/remove_short_trajectories.feather
    - data/auditing/split_data_test.feather
    - data/auditing/split_data_train.feather
    - data/auditing/split_data_val.feather
    - data/auditing/split_trajectories_at_events.feather
    - data/auditing/split_trajectories_at_gaps.feather
    - data/clean_data/baseline.feather
    - data/clean_data/inr.feather
    - data/clean_data/events.feather
    - data/clean_data/merged.feather
    - data/clean_data/train_data.feather
    - data/clean_data/val_data.feather
    - data/clean_data/test_data.feather
    - scripts/audit_combine_preprocessing.py
    params:
    - preprocess
    - data
    outs:
    - output/combine_preprocess_audit.txt:
        cache: false
    - data/auditing/inr_dose_change_tile.png:
        cache: false
    - data/auditing/dose_change_inr_change_tile.png:
        cache: false
  tune_behavior_cloner:
    cmd: python3 scripts/tune_bc.py
    deps:
    - data/clean_data/train_data.feather
    - data/clean_data/val_data.feather
    - scripts/tune_bc.py
    params:
    - data.events_to_keep
    - data.events_to_split
    - data.min_train_trajectory_length
    - data.state_columns
    - replay_buffer.init.time_varying
    - replay_buffer.init.include_dose_time_varying
    - behavior_cloner
    outs:
    - ray_logs/bc
  select_behavior_cloner:
    cmd: python3 scripts/choose_bc.py
    deps:
    - data/clean_data/train_data.feather
    - data/clean_data/val_data.feather
    - scripts/choose_bc.py
    params:
    - behavior_cloner
    outs:
    - output/behavior_cloner_wis
  tune_dsbcq:
    cmd: python3 scripts/tune_smdp_dbcq.py
    deps:
    - data/clean_data/train_data.feather
    - data/clean_data/val_data.feather
    - scripts/tune_smdp_dbcq.py
    params:
    - data.events_to_keep
    - data.events_to_split
    - data.min_train_trajectory_length
    - data.state_columns
    - replay_buffer.init.time_varying
    - replay_buffer.init.include_dose_time_varying
    - dsbcq
    outs:
    - ray_logs/dbcq
