stages:
  convert_baseline:
    cmd: python3 scripts/convert_sas_to_feather.py --input_filename data/raw_data/merged_baseline.sas7bdat
      --output_filename data/raw_data/baseline.feather
    deps:
    - data/raw_data/merged_baseline.sas7bdat
    - scripts/convert_sas_to_feather.py
    outs:
    - data/raw_data/baseline.feather
  convert_inr:
    cmd: python3 scripts/convert_sas_to_feather.py --input_filename data/raw_data/merged_inr.sas7bdat
      --output_filename data/raw_data/inr.feather
    deps:
    - data/raw_data/merged_inr.sas7bdat
    - scripts/convert_sas_to_feather.py
    outs:
    - data/raw_data/inr.feather
  convert_events:
    cmd: python3 scripts/convert_sas_to_feather.py --input_filename data/raw_data/merged_events.sas7bdat
      --output_filename data/raw_data/events.feather
    deps:
    - data/raw_data/merged_events.sas7bdat
    - scripts/convert_sas_to_feather.py
    outs:
    - data/raw_data/events.feather
  preprocess:
    cmd: python3 scripts/preprocess_combine_af.py --baseline_path data/raw_data/baseline.feather
      --inr_path data/raw_data/inr.feather --events_path data/raw_data/events.feather
      --output_directory data/clean_data
    params:
    - preprocess.static_state_columns
    - preprocess.dose_outlier_threshold
    - preprocess.event_range
    - data.events_to_keep
    deps:
    - data/raw_data/baseline.feather
    - data/raw_data/events.feather
    - data/raw_data/inr.feather
    - scripts/preprocess_combine_af.py
    outs:
    - data/clean_data/baseline.feather
    - data/clean_data/inr.feather
    - data/clean_data/events.feather
    - data/clean_data/merged.feather
    - data/clean_data/train_data.feather
    - data/clean_data/val_data.feather
    - data/clean_data/test_data.feather
    - data/auditing
  audit_preprocess:
    cmd: python3 scripts/audit_combine_preprocessing.py > output/combine_preprocess_audit.txt
    deps:
    - data/auditing
    - data/clean_data
    params:
    - preprocess.static_state_columns
    - data.events_to_keep
  tune_behavior_cloner:
    cmd: python3 scripts/tune_bc.py --smoke_test
    deps:
    - data/clean_data/train_data.feather
    - data/clean_data/val_data.feather
    params:
    - replay_buffer.min_train_trajectory_length
    - replay_buffer.state.include_dose_time_varying
    - behavior_cloner
