preprocess:
  static_state_columns:
  - SEX
  - RACE2
  - SMOKE
  - BMED_ASPIRIN
  - BMED_AMIOD
  - DIABETES
  - HX_CHF
  - HYPERTENSION
  - HX_MI
  - BMED_THIENO
  - AGE_DEIDENTIFIED
  - WEIGHT
  dose_outlier_threshold: 140
  event_range: 90

data:
  events_to_keep:
    DEATH: Death
    STROKE: Ischemic Stroke
    MAJOR_BLEED: Major Bleeding
    MINOR_BLEED: Minor Bleeding
    HEM_STROKE: Hemorrhagic Stroke
    HOSP: Hospitalization
    SYS_EMB: Systemic Embolism
  min_train_trajectory_length: 5

replay_buffer:
  discount_factor: 0.99
  include_dose_time_varying: false

behavior_cloner:
  tune_seed: 42
  min_training_epochs: 100
  max_training_epochs: 500
  target_metric: val/auroc
  target_mode: max
  hyperparams:
    init_seed:
    - 0
    - 1
    - 2
    likelihood:
    - discrete
    learning_rate:
    - 1.e-4
    batch_size:
    - 16
    num_layers:
    - 2
    - 3
    hidden_dim:
    - 16
    - 128
    weight_option_frequency:
    - false
