data:
    static_state_columns:
        - SEX
        - RACE2
        - SMOKE
        - BMED_ASPIRIN
        - BMED_AMIOD
        - DIABETES
        - HX_CHF
        - HYPERTENSION
        - HX_MI
        - BMED_THIENO
        - AGE_DEIDENTIFIED
        - WEIGHT
    dose_outlier_threshold: 140
    events_to_keep:
        DEATH: Death
        STROKE: Ischemic Stroke
        MAJOR_BLEED: Major Bleeding
        MINOR_BLEED: Minor Bleeding
        HEM_STROKE: Hemorrhagic Stroke
        HOSP: Hospitalization
        SYS_EMB: Systemic Embolism
    event_range: 90
