preprocess:
  static_state_columns:
  - SEX
  - RACE2
  - SMOKE
  - BMED_ASPIRIN
  - BMED_AMIOD
  - DIABETES
  - HX_CHF
  - HYPERTENSION
  - HX_MI
  - BMED_THIENO
  - AGE_DEIDENTIFIED
  - WEIGHT
  dose_outlier_threshold: 140
  event_range: 90

data:
  events_to_keep:
    DEATH: Death
    STROKE: Ischemic Stroke
    MAJOR_BLEED: Major Bleeding
    MINOR_BLEED: Minor Bleeding
    HEM_STROKE: Hemorrhagic Stroke
    HOSP: Hospitalization
    SYS_EMB: Systemic Embolism

replay_buffer:
  discount: 0.99
  min_train_trajectory_length: 5
  state:
    include_dose_time_varying: false

behavior_cloner:
  tune_seed: 42
  init_seeds:
  - 0
  - 1
  - 2
  - 3
  likelihood: discrete
  learning_rate: 1e-4
  batch_size:
  - 16
  - 128
  num_layers: 2
  hidden_dim: 64
  weight_option_frequency: false
  min_training_epochs: 100
  max_training_epochs: 500
