
# coding: utf-8

"""
Defining constants.
"""

DOSE_OUTLIER_THRESHOLD = 140
MAX_TIME_ELAPSED = 90
MIN_INR_COUNTS = 10

EVENTS_TO_KEEP = ['DEATH', 'STROKE', 'MAJOR_BLEED', 'MINOR_BLEED', 'HEM_STROKE', 'HOSP']
STATIC_STATE_COLS = ["SEX", "CONTINENT", "SMOKE", "BMED_ASPIRIN", "BMED_AMIOD", "DIABETES", "HX_CHF",
                         "HYPERTENSION", 'HX_MI', "BMED_THIENO", "AGE_DEIDENTIFIED", "WEIGHT"]

ADV_EVENTS = ["STROKE", "HEM_STROKE", "MAJOR_BLEED"]

STATE_COLS_TO_FILL = ['INR_VALUE','SEX', 'BMED_ASPIRIN', 'BMED_AMIOD', 'DIABETES', 'HX_CHF','HYPERTENSION','HX_MI','BMED_THIENO',            
                     'AGE_DEIDENTIFIED', 'MINOR_BLEED_FLAG','MAJOR_BLEED_FLAG','HOSP_FLAG','WEIGHT','WARFARIN_DOSE','CONTINENT_EAST ASIA',  
                     'CONTINENT_EASTERN EUROPE', 'CONTINENT_LATIN AMERICA', 'CONTINENT_NORTH AMERICA','CONTINENT_SOUTH ASIA',                  
                     'CONTINENT_WESTERN EUROPE', 'SMOKE_CURRENT SMOKER','SMOKE_FORMER SMOKER', 'SMOKE_NEVER SMOKED','INR_VALUE_BIN_<=1.5',
                     'INR_VALUE_BIN_(1.5, 2)', 'INR_VALUE_BIN_[2, 3]', 'INR_VALUE_BIN_(3, 3.5)', 'INR_VALUE_BIN_>=3.5','WARFARIN_DOSE_BIN_<=5',
                     'WARFARIN_DOSE_BIN_(5, 12.5]','WARFARIN_DOSE_BIN_(12.5, 17.5]','WARFARIN_DOSE_BIN_(17.5, 22.5]','WARFARIN_DOSE_BIN_(22.5, 27.5]',
                     'WARFARIN_DOSE_BIN_(27.5, 30]', 'WARFARIN_DOSE_BIN_(30, 32.5]','WARFARIN_DOSE_BIN_(32.5, 35]','WARFARIN_DOSE_BIN_(35, 45]', 
                     'WARFARIN_DOSE_BIN_>45', 'AGE_BIN_<=50', 'AGE_BIN_(50, 60]', 'AGE_BIN_(60, 65]', 'AGE_BIN_(65, 70]',
                     'AGE_BIN_(70, 75]','AGE_BIN_(75, 80]','AGE_BIN_>80','WEIGHT_BIN_<=55', 'WEIGHT_BIN_(55, 70]', 
'WEIGHT_BIN_(70, 80]', 'WEIGHT_BIN_(80, 90]', 'WEIGHT_BIN_(90, 100]', 'WEIGHT_BIN_>100']